export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const ENABLE_RETURN_FLIGHT = 'ENABLE_RETURN_FLIGHT';
export const DISABLE_RETURN_FLIGHT = 'DISABLE_RETURN_FLIGHT';

export const SEARCH_CITIES_REQUEST = 'SEARCH_CITIES_REQUEST';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCESS';
export const SEARCH_CITIES_FAILURE = 'SEARCH_CITIES_FAILURE';

export const FILTER_RANGE = 'FILTER_RANGE';
